version: '3.7'
services:
  blog-postgres:
#    env_file: .env
    image: postgres:9.6.22-alpine
    container_name: go_blog_db
    environment:
      - POSTGRES_USER=sammi
      - POSTGRES_PASSWORD=sammi
      - POSTGRES_DB=goblog
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - blog

volumes:
  api:
  database_postgres:
  # database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  blog:
