### create a account
POST localhost:5000/api/v1/accounts
Accept: application/json
Content-Type: application/json

{
  "name": "sammidev",
  "email": "sammidev@gmail.com",
  "password": "sammidev123"
}

### get accounts
GET localhost:5000/api/v1/accounts
Accept: application/json

### get account by id
GET localhost:5000/api/v1/accounts/1
Accept: application/json

### login with account has created for get token
POST localhost:5000/api/v1/accounts/auth
Accept: application/json
Content-Type: application/json

{
  "email": "sammidev@gmail.com",
  "password": "sammidev123"
}

### update account
PUT localhost:5000/api/v1/accounts/1
Authorization: Bearer TOKEN
Accept: application/json
Content-Type: application/json

{
  "name": "sam update 2",
  "email": "sam_update_2@gmail.com"
}

### change password
PUT localhost:5000/api/v1/accounts/1/password
Authorization: Bearer TOKEN
Accept: application/json
Content-Type: application/json

{
  "old_password": "sammidev123",
  "new_password": "sammi_izzah"
}

### delete account
DELETE localhost:5000/api/v1/accounts/1
Authorization: Bearer TOKEN

### create a post
POST localhost:5000/api/v1/posts
Authorization: Bearer TOKEN
Accept: application/json
Content-Type: application/json

{
   "title": "o Recipe for Professionals",
   "body": "o Recipe for Professionals"
}

### get posts
GET localhost:5000/api/v1/posts
Accept: application/json

### get post by id
GET localhost:5000/api/v1/posts/1
Accept: application/json

### update post by id
PUT localhost:5000/api/v1/posts/1
Authorization: Bearer TOKEN
Accept: application/json
Content-Type: application/json

{
  "title": "Kotlin Recipe for Professionals",
  "body": "Kotlin Recipe for Professionals ... ... ... "
}

### delete post by id
DELETE localhost:5000/api/v1/posts/1
Authorization: Bearer TOKEN